export enum EventType {
  PushEvent = "PushEvent",
  PullRequestEvent = "PullRequestEvent",
  IssueEvent = "IssueEvent",
  CommitCommentEvent = "CommitCommentEvent",
  CreateEvent = "CreateEvent",
  DeleteEvent = "DeleteEvent",
  ForkEvent = "ForkEvent",
  WatchEvent = "WatchEvent",
  ReleaseEvent = "ReleaseEvent",
  PublicEvent = "PublicEvent",
  IssueCommentEvent = "IssueCommentEvent",
  PullRequestReviewCommentEvent = "PullRequestReviewCommentEvent",
  PullRequestReviewEvent = "PullRequestReviewEvent",
}
